apiVersion: v1
kind: Pod
metadata:
  name: dms-registry
  labels:
    app: dms-registry
spec:
  containers:
    - name: dms-registry-container
      image: org.example.dms.registry/registry
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8761
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi