

server:
  port: 55002
  servlet:
    context-path: /service-auth



eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  sleuth:
    enabled: true
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://linux.local:3306/example
    username: root
    password: abcd.1234
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: couchbase
    couchbase:
      expiration: 1h
  couchbase:
    connection-string: