server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true

spring:
  application:
    name: proxy
  sleuth:
    enabled: true
    sampler:
      probability: 1
    zuul:
      enabled: true
    async:
      configurer:
        enabled: true
      enabled: true

zuul:
  ribbon:
    eager-load:
      enabled: true
#  sensitive-headers: Cookie, Set-Cookie

ribbon:
  eureka:
    enabled: true

logging:
  level:
    com.netflix: INFO
  file:
    name: /Users/mxia/logs/proxy.log

management:
  endpoints:
    web:
      exposure:
        include: health, info, routes

security:
  jwt:
    header: Authorization
    prefix: Bearer
    key: 7R9SATCVDWEXGZH2J4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7Q8SATBUCWEXFY
