server:
  port: 55002

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://linux.local:8761/eureka/}

spring:
  application:
    name: oauth
  sleuth:
    enabled: true
    sampler:
      probability: 1
  datasource:
    url: jdbc:postgresql://linux.local:5432/admin
    username: postgres
    password: abcd.1234
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    type: redis
    redis:
      time-to-live: 1h
  redis:
    port: 6379
    host: linux.local

key: 7R9SATCVDWEXGZH2J4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7Q8SATBUCWEXFY
logging:
  file:
    name: /Users/mxia/logs/oauth.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"

