

server:
  port: 55001



eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: proxy-service
  sleuth:
    enabled: true
    sampler:
      probability: 1
