apiVersion: v1
kind: Pod
metadata:
  name: dms-proxy
  labels:
    app: dms-proxy
spec:
  containers:
    - name: dms-registry-container
      image: org.example.dms.proxy/proxy
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi